Fix device details screen corruption for failed array members. Format devices even if we can't disable qerr. Print LID path in flit macro in iprdbg. Fix iprupdate init.d status. Fix init.d scripts to work with yast2.

diff --git a/init.d/iprupdate b/init.d/iprupdate
--- a/init.d/iprupdate
+++ b/init.d/iprupdate
@@ -41,19 +41,36 @@ start() {
 }
 
 stop() {
-    exit 3
+    echo -n "Shutting down ipr update daemon"
+    log_success_msg " "
+    return 0
 }
 
 restart() {
-    exit 3
+    $0 stop
+    $0 start
+    return $RETVAL
 }
 
 reload() {
-    exit 3
+    $0 stop
+    $0 start
+    return $RETVAL
 }
 
 status() {
-    exit 3
+	echo -n "Checking ipr microcode levels"
+	$IPRUPDATE --check_only
+
+	RETVAL=$?
+	if [ $RETVAL -eq 0 ]; then
+	    log_success_msg " "
+	else
+	    echo " "
+	    echo -n "ipr microcode updates required"
+	    log_success_msg " "
+	fi
+        return $RETVAL
 }
 
 case "$1" in
